#!/usr/bin/env bash
set -o errexit
set -o nounset

if test "$#" -ge 2 && test "$1" = "-c"; then
  fmt=$2
  shift 2
  if test "$fmt" = "%a"; then
    if test "$#" -eq 0; then
      /usr/bin/stat -f '%Lp' .
    else
      for path in "$@"; do
        /usr/bin/stat -f '%Lp' "$path"
      done
    fi
    exit 0
  fi
fi

if command -v gstat >/dev/null 2>&1; then
  exec gstat "$@"
fi
exec /usr/bin/stat "$@"
